version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g pnpm
      - export COMMIT_SHA=$(cat meta.json | jq -r '.sha')
      - echo $COMMIT_SHA
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - ls -a
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
  pre_build:
    commands:
      - pwd
      - ls -lah
      - pulumi version
      - pnpm install
      - pnpm -C website install && pnpm -C website build
      - cd tests && pnpm install && npx playwright install --with-deps && cd ..
      - cd infra/lambda && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra/cloudfront && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra && pnpm install && pnpm run lambda:up && pnpm run lambda:export && pnpm run cloudfront:up && pnpm run cloudfront:export && cd ../
  build:
    commands:
      - ls -a
      - cd tests && pnpm test
    finally:
      - cd ../
      - echo $COMMIT_SHA
      - cd infra && pnpm cloudfront:destroy && pnpm lambda:destroy && cd ../
