version: 0.2

phases:
  build:
    commands:
      # $CODEBUILD_SRC_DIR => rc branch
      # $CODEBUILD_SRC_DIR_SourceArtifact => topic branch
      - cd $CODEBUILD_SRC_DIR_SourceArtifact
      - git status
      - cp $CODEBUILD_SRC_DIR/buildspec-e2e.yml buildspec-e2e.yml
      - cp $CODEBUILD_SRC_DIR/buildspec-mock-e2e.yml buildspec-mock-e2e.yml
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR_SourceArtifact
