version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g pnpm
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - ls -a
      - wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
      - echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
      - sudo apt update && sudo apt install terraform
      - terraform version
      - cd e2e/infra/terraform && terraform init && cd -
  pre_build:
    commands:
      - pwd
      - ls -lah
      - terraform version
      - pnpm install
      - pnpm build
      #- cp -r dist e2e
      - pnpm -C e2e/website install && pnpm -C e2e/website build
      - cd e2e/tests && pnpm install && npx playwright install --with-deps && cd -
  build:
    commands:
      - ls -a
      - cd e2e/infra/terraform && pnpm test && cd -
    finally:
      - echo $COMMIT_SHA
      - cd e2e/infra/terraform && terraform destroy
