version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g pnpm
      - echo $COMMIT_ID
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - ls -a
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
      - pnpm install
      - cd e2e/tests && npx playwright install --with-deps && cd ../..
      - pnpm -C e2e/website install && pnpm -C e2e/website build
      - UNPACK_TO_DIST=true node scripts/downloadGithubRelease.mjs
  pre_build:
    commands:
      - pwd
      - pulumi version
      - cd e2e/infra/lambda && pulumi stack init e2e && pulumi stack select e2e && cd ../../..
      - cd e2e/infra/cloudfront && pulumi stack init e2e && pulumi stack select e2e && cd ../../..
      - cd e2e/infra && pnpm run lambda:up && pnpm run lambda:export && pnpm run cloudfront:up && pnpm run cloudfront:export && cd ../..
  build:
    commands:
      - ls -a
      - cd e2e/tests && pnpm test
    finally:
      - cd ../..
      - echo $COMMIT_ID
      - cd e2e/infra && pnpm cloudfront:destroy && pnpm lambda:destroy && cd ../..
