# todo use this file and delete hard coded code editor
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g pnpm
      - export COMMIT_SHA=$(git rev-parse HEAD)
      - export VERSION=$(cat package.json | jq -r '.version')
      - echo $COMMIT_SHA
      - echo $VERSION
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - ls -a
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
  pre_build:
    commands:
      - pwd
      - ls -lah
      - pulumi version
      - pnpm install
      - FPCDN=$MOCK_FPCDN INGRESS_API=$MOCK_INGRESS_API pnpm build
      - npm i -g ts-node
      - pnpm -C e2e/website install && pnpm -C e2e/website build
      - cd e2e/tests && pnpm install && cd -
      - cd e2e/infra/lambda && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd -
      - cd e2e/infra/cloudfront && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd -
      - cd e2e/infra && pnpm install && pnpm run lambda:up && pnpm run lambda:export && pnpm run cloudfront:up && pnpm run cloudfront:export && cd -
  build:
    commands:
      - ts-node e2e/scripts/mockTests.ts --project=tsconfig.json
    finally:
      - echo $COMMIT_SHA
      - cd e2e/infra && pnpm cloudfront:destroy && pnpm lambda:destroy && cd -

