version: 0.2
env:
  secrets-manager:
    GITHUB_TOKEN: "fpjs-dev-cloudfront-secrets:GITHUB_TOKEN"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm i -g pnpm
      - export COMMIT_SHA=$(cat meta.json | jq -r '.sha')
      - echo $COMMIT_SHA
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
          -d "{\"state\":\"pending\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/fpjs-dev-cloudfront-lambda-e2e-mock-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"Mock E2E Tests are running\",\"context\":\"mock-e2e\"}"
      - ls -a
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
  pre_build:
    commands:
      - pwd
      - ls -lah
      - pulumi version
      - pnpm install
      - npm i -g ts-node
      - pnpm -C website install && pnpm -C website build
      - cd tests && pnpm install && cd ..
      - cd infra/lambda && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra/cloudfront && pnpm install && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra && pnpm install && pnpm run lambda:up && pnpm run lambda:export && pnpm run cloudfront:up && pnpm run cloudfront:export && cd ../
    finally:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
            -d "{\"state\":\"error\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/fpjs-dev-cloudfront-lambda-e2e-mock-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"Mock E2E Tests failed during the pre-build step\",\"context\":\"mock-e2e\"}"
        fi
  build:
    commands:
      - ts-node ./scripts/mockTests.ts --project=tsconfig.json
    finally:
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $COMMIT_SHA
      - export STATUS=$(sh ./scripts/get-codebuild-status.sh)
      - echo $STATUS
      - |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
          -d "{\"state\":\"$STATUS\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/fpjs-dev-cloudfront-lambda-e2e-mock-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"Mock E2E Tests finished\",\"context\":\"mock-e2e\"}"
      - cd infra && pnpm cloudfront:destroy && pnpm lambda:destroy && cd ../

