version: 0.2
env:
  secrets-manager:
    GITHUB_TOKEN: "fpjs-dev-cloudfront-secrets:GITHUB_TOKEN"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - export COMMIT_SHA=$(cat meta.json | jq -r '.sha')
      - echo $COMMIT_SHA
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_PUBLIC_BUILD_URL
      - |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
          -d "{\"state\":\"pending\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/$AWS_ACCOUNT_ID/projects/fpjs-dev-cloudfront-lambda-e2e-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"E2E tests are running\",\"context\":\"e2e\"}"
      - ls -a
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
      - pnpm install && pnpm -C infra install && pnpm -C website install && pnpm -C tests install
      - cd tests && npx playwright install --with-deps && cd ..
  pre_build:
    commands:
      - pwd
      - pulumi version
      - cd website && pnpm build && cd ../
      - cd infra/lambda && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra/cloudfront && pulumi stack init e2e && pulumi stack select e2e && cd ../../
      - cd infra && pnpm lambda:up && pnpm lambda:export && pnpm cloudfront:up && pnpm cloudfront:export && cd ../
    finally:
      - |
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
            -d "{\"state\":\"error\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/$AWS_ACCOUNT_ID/projects/fpjs-dev-cloudfront-lambda-e2e-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"E2E tests failed during the pre-build step\",\"context\":\"e2e\"}"
        fi
  build:
    commands:
      - ls -a
      - cd tests && pnpm test
    finally:
      - cd ../
      - echo $CODEBUILD_BUILD_SUCCEEDING
      - echo $COMMIT_SHA
      - export STATUS=$(sh ./scripts/get-codebuild-status.sh)
      - echo $STATUS
      - |
        curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/fingerprintjs/fingerprint-pro-cloudfront-integration/statuses/$COMMIT_SHA \
          -d "{\"state\":\"$STATUS\",\"target_url\":\"https://us-east-1.console.aws.amazon.com/codesuite/codebuild/$AWS_ACCOUNT_ID/projects/fpjs-dev-cloudfront-lambda-e2e-tests/build/$CODEBUILD_BUILD_ID/?region=us-east-1\",\"description\":\"E2E tests finished\",\"context\":\"e2e\"}"
      - cd infra && pnpm cloudfront:destroy && pnpm lambda:destroy && cd ../
