version: 0.2

phases:
  build:
    commands:
      - ls -la $CODEBUILD_SRC_DIR # rc branch, also called as primary source
      - ls -la $CODEBUILD_SRC_DIR_SourceArtifact # source that will be used for topic branch
      - cd $CODEBUILD_SRC_DIR_SourceArtifact
      - echo $BRANCH_NAME
      - git switch $BRANCH_NAME # check out topic branch
      - git status
      - cp $CODEBUILD_SRC_DIR/buildspec-e2e.yml buildspec-e2e.yml
      - cp $CODEBUILD_SRC_DIR/buildspec-mock-e2e.yml buildspec-mock-e2e.yml
artifacts:
  files:
  base-directory: $CODEBUILD_SRC_DIR_SourceArtifact
