version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
      - pulumi login --local
      - yarn install && yarn install --cwd=e2e/infra && yarn install --cwd=e2e/website
  build:
    commands:
      - pulumi version
      - yarn build
      - cd e2e/website && yarn build && cd ../../
      - cd e2e/infra/lambda && pulumi stack init e2e && pulumi stack select e2e && pulumi config set org fpjs && cd ../../../
      - cd e2e/infra && yarn lambda:up
      - echo "Running tests..."
    finally:
      - yarn lambda:destroy && cd ../../
  post_build:
    commands:
      - echo "Running post build..."
