version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://get.pulumi.com | sh
      - export PATH=$PATH:$HOME/.pulumi/bin
      - pulumi version
      - yarn install && yarn install --cwd=e2e/infra && yarn install --cwd=e2e/website
  build:
    commands:
      - pulumi version
      - yarn build
      - yarn build --cwd=e2e/website
      - yarn up --cwd=e2e/infra
      - echo "Running tests..."
    finally:
      - cd e2e/infra && yarn down
  post_build:
    commands:
      - echo "Running post build..."
