name: Coverage

on:
  push:
    branches:
      - main

jobs:
  generate-docs-and-coverage:
    name: Generate docs and coverage report
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/docs-and-coverage.yml@v1
    with:
      skip-docs-step: true
      prepare-gh-pages-commands: |
        mv coverage/lcov-report/* ./gh-pages/
