name: Deploy test branch
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'cloudformation/*.yml'

jobs:
  deploy-test-branch:
    name: Deploy test branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Get pnpm store directory path
        id: pnpm-store-dir-path
        run: echo "dir=$(pnpm store path)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: pnpm-cache # use this to check for `cache-hit` (`steps.pnpm-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          FPCDN: ${{ secrets.FPCDN }}
          INGRESS_API: ${{ secrets.INGRESS_API }}

      - name: Collect meta
        run: node .github/workflows/serialize_job_info.js
        env:
          GITHUB_REAL_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Prepare e2e directory
        run: cp -r dist e2e && cp package.json e2e && cp pnpm-lock.yaml e2e

      - name: Deploy
        uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e
        env:
          REPO: self
          BRANCH: e2e-tests
          FOLDER: e2e
          TARGET_DIR: ${{ steps.date.outputs.today }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Deploy prepared in [${{ steps.date.outputs.today }}]

