name: Deploy test branch
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - 'cloudformation/*.yml'

jobs:
  deploy-test-branch:
    name: Deploy test branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Install pnpm'
        uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9

      - name: 'Install latest node version'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: ${{ env.PACKAGE_MANAGER }}

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          FPCDN: ${{ secrets.FPCDN }}
          INGRESS_API: ${{ secrets.INGRESS_API }}

      - name: Collect meta
        run: node .github/workflows/serialize_job_info.js
        env:
          GITHUB_REAL_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Prepare e2e directory
        run: cp -r dist e2e && cp package.json e2e && cp pnpm-lock.yaml e2e

      - name: Build for mock tests
        run: rm -rf dist && pnpm build
        env:
          FPCDN: ${{ secrets.MOCK_FPCDN }}
          INGRESS_API: ${{ secrets.MOCK_INGRESS_API }}

      - name: Add mock dist
        run: cp -r dist e2e/mock-dist

      - name: Deploy
        uses: s0/git-publish-subdir-action@92faf786f11dfa44fc366ac3eb274d193ca1af7e
        env:
          REPO: self
          BRANCH: e2e-tests
          FOLDER: e2e
          TARGET_DIR: ${{ steps.date.outputs.today }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: Deploy prepared in [${{ steps.date.outputs.today }}]

