name: Publish CloudFront integration
on:
  pull_request: 
env:
  AWS_IAM_AUTH_REGION: us-east-1
  TIER: use1
  REGION: us-east-1
  ENV: release
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:

  
  deploy-to-s3:
    # Skip for pre-releases
    #if: ${{ !github.event.release.prerelease }}
    name: Deploy artifact to S3 bucket
    #environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@129abb77bf5884e578fcaf1f37628e41622cc371
        with:
          version: 9
        
      - run: pnpm install
 
      - name: Configure AWS credentials from dev account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::421367603048:role/github_eb_ci_cd
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_IAM_AUTH_REGION }}

      - run: yarn build && yarn prepare-package
      
      - name: Upload files
        run: |
          aws s3api put-object --body lambda_latest.zip --bucket fingerprint-pro-cloudfront-integration --key testing/lambda_latest_test.zip
          aws s3api put-object --body mgmt_lambda_latest.zip --bucket fingerprint-pro-cloudfront-integration --key testing/mgmt_lambda_latest_test.zip
          aws s3api put-object --body cloudformation/template.yml --bucket fingerprint-pro-cloudfront-integration --key testing/template_test.yml
