name: Publish CloudFront integration
on:
  pull_request: 
env:
  AWS_IAM_AUTH_REGION: us-east-1
  TIER: use1
  REGION: us-east-1
  ENV: release
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:

  
  deploy-to-s3:
    # Skip for pre-releases
    #if: ${{ !github.event.release.prerelease }}
    name: Deploy artifact to S3 bucket
    #environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup k8 Runner
        id: setup-k8-runner
        uses: ./.github/actions/k8-setup-runner
 
      - name: Configure AWS credentials from dev account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::421367603048:role/github_eb_ci_cd
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_IAM_AUTH_REGION }}

      - name: Get files
        run: |
          aws s3api get-object --bucket fingerprint-pro-cloudfront-integration --key lambda_latest.zip lambda_latest.zip
