name: Release

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'A type of version bump'
        default: 'patch'
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Release new version
    runs-on: ubuntu-20.04

    permissions:
      contents: write
      pull-requests: write
      
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v3
        with:
          ref: develop
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
        
      - name: Set git settings
        uses: fregante/setup-git-user@v1

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Run tests
        run: yarn test

      - name: Disable version tags
        run: yarn config set version-git-tag false

      - name: Bump version
        run: yarn version --${{ github.event.inputs.version_bump }}

      - name: Build lambda function
        run: yarn build

      - name: Run type check
        run: yarn test:dts

      - name: Get new version
        id: version      
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'package.json'
          prop_path: 'version'

      - name: Commit and push new version of lambda
        run: |
          git commit package.json dist/ -m "build: new scripts v${{steps.version.outputs.prop}}"
          git push "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          git tag -a "v${{steps.version.outputs.prop}}" -m "v${{steps.version.outputs.prop}}"
          git push --tags "https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

      - name: Create a Github release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{steps.version.outputs.prop}}
          name: Release ${{steps.version.outputs.prop}}

      - name: Create Pull Request from develop to main
        id: create_pr
        uses: devops-infra/action-pull-request@v0.5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: develop
          target_branch: main
          title: New version of scripts v${{ steps.version.outputs.prop }}
          body: New version of scripts v${{ steps.version.outputs.prop }}

      - name: Check PR outputs
        if: ${{ steps.create_pr.outputs.url }}
        run: echo "Pull Request URL - ${{ steps.create_pr.outputs.url }}"
